name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install
      
    - name: Update Posts Index
      run: node scripts/update-posts-index.js
      
    - name: Commit Posts Index Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/posts/README.md docs/README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "自动更新文章索引 [skip ci]"
        git push

    - name: Build
      run: npm run build

    - name: Create .nojekyll file
      run: touch docs/.vuepress/dist/.nojekyll

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/.vuepress/dist
        cname: 
        force_orphan: true
        commit_message: "部署更新 [skip ci]"